version: "3.9"
services:
  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - redis
  web:
    build:
      context: .
      args:
        BUNDLE_GEMS__CONTRIBSYS__COM: $BUNDLE_GEMS__CONTRIBSYS__COM
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - redis
